### ISSUE TITLE
Option to Specify Output Needed

### ISSUE THREAD

**Issue by andydish** [halelab/GBS-SNP-CROP#11]
I'm trying to run your scripts on a cluster, and am having a slight issue with the input and output file paths specified in your program.  I'd like to be able to specify different input and output paths from the command line, rather than having to manually edit the output file paths in each of your scripts.  Would it be at all possible for you to add a command line option for output file path?

I'd really appreciate it-otherwise your program has been working great for my data!

**Comment by halelab** [comment]
Hi @andydish 

I really apologize for never answer back to you. I support the google group and sometimes I look at here. Sorry.
The GBS-SNP-CROP was written to save the outputs in appropriated directories, which is easy to keep track of the outputs and potential errors.

Best,
Arthur
