### ISSUE TITLE
Step#3: demultiplex

### ISSUE THREAD

**Issue by cryptic0** [halelab/GBS-SNP-CROP#12]
It is not clear whether the demultiplexing step requires a plain text fastq file or if it can work with fastq.gz files.  Documentation example states the following:

-fq FileNameSeed_R1_001.fastq.gz

My seed is TREES for the input file TREES_R1_001.fastq.gz

But I keep getting the following errors:

- Can't open FASTQ file: No such file or directory
- Creating genotype-specific FASTQ files from TREES_SE_R1parsed.fastq. file

The second error message suggest that the #3 perl script is expecting files named in the following fashion:
FileNameSeed_SE_R1parsed.fastq

Thus, there seems to be a conflict between the documentation and what the program is actually expecting.

**Comment by halelab** [comment]
Hi, 

Thank you for alert us about this. The step 3 uses the output from step 2 which is a plain fastq file. Sorry for this mistake on wiki page. I'll update it.
