### ISSUE TITLE
Link to download Pear and licensing have changed

### ISSUE THREAD

**Issue by dsenalik** [halelab/GBS-SNP-CROP#13]
The link to Pear in README.md
http://sco.h-its.org/exelixis/web/software/pear/
contains broken links or under construction pages without content, and the github repository referred to at that url in the download instructions has been deleted.
It appears that Pear has been changed to a licensed program (commercial or academic), and the new link to download is
https://www.h-its.org/en/research/sco/software/#NextGenerationSequencingSequenceAnalysis

**Comment by arthurmelobio** [comment]
Thank you @dsenalik for let us know. I'm gonna update the links right now.
