### ISSUE TITLE
Step3.Demultiplexing_message_all_Done_but_empty_fastq_outputs

### ISSUE THREAD

**Issue by el42008** [halelab/GBS-SNP-CROP#8]
Hi, 

I am trying to demultiplex my samples using the 3 script. I provided the barcode ID files as asked and teh seed_name of my PE_R1 and R2parsed.fastq files obtained with script2. The scripts works fine as checked in the error file, and gives me the message 
 DONE
 Please, see the 'demultiplexed' directory
But all I get is all the files of the genotypes but empty. So it does the ./multiplexed directory and produces all the 48 files taht correspond with the genotypes but the end up empty.

Thank you very much

**Comment by arthurmelobio** [comment]
Hi, 

Please, check a coulpe of things:
1. Blank spaces in your barcode ID file. 
2. The barcode sequence attached in the end of each read header.
3. If you are using the correct -d flag for your data type. 

Please, use the google group for the next questions ...

Thanks,
Arthur.

**Comment by el42008** [comment]
Thanks, 

I have checked all and I have another question I posted in google group. Thanks very much for asking so quick
