### ISSUE TITLE
The tutorial is not runnable...

### ISSUE THREAD

**Issue by ALTree** [halelab/GBS-SNP-CROP#9]
because several scripts split the lines in `barcodesID.txt` by tabs:

```perl
my @barcode_ID = split("\t", $barcodesID);
```

but the `barcodesID.txt` file in the `tutorial` folder has space-separated columns. For this reason, the pipeline fails to process the  `tutorial` data.

**Comment by arthurmelobio** [comment]
Thank's Alberto, it was updated.

**Comment by ALTree** [comment]
Thanks for the quick response.
